-- Migration 019 (DOWN)
-- Revert canonical inventory movement ledger normalization.

BEGIN TRANSACTION;

DROP TRIGGER IF EXISTS trg_inventory_adjustment_lines_to_inventory_movement_ledger_insert_v019;
DROP TRIGGER IF EXISTS trg_transfer_order_lines_to_inventory_movement_ledger_insert_v019;
DROP TRIGGER IF EXISTS trg_po_receipt_lines_to_inventory_movement_ledger_insert_v019;
DROP TRIGGER IF EXISTS trg_sales_transactions_to_inventory_movement_ledger_insert_v019;

DROP TRIGGER IF EXISTS trg_inventory_movement_ledger_adjustment_alignment_update_v019;
DROP TRIGGER IF EXISTS trg_inventory_movement_ledger_adjustment_alignment_insert_v019;
DROP TRIGGER IF EXISTS trg_inventory_movement_ledger_transfer_alignment_update_v019;
DROP TRIGGER IF EXISTS trg_inventory_movement_ledger_transfer_alignment_insert_v019;
DROP TRIGGER IF EXISTS trg_inventory_movement_ledger_po_receipt_alignment_update_v019;
DROP TRIGGER IF EXISTS trg_inventory_movement_ledger_po_receipt_alignment_insert_v019;
DROP TRIGGER IF EXISTS trg_inventory_movement_ledger_sale_alignment_update_v019;
DROP TRIGGER IF EXISTS trg_inventory_movement_ledger_sale_alignment_insert_v019;

DROP VIEW IF EXISTS v_inventory_movement_reconciliation;

DROP INDEX IF EXISTS idx_inventory_movement_ledger_location_movement_at_v019;
DROP INDEX IF EXISTS idx_inventory_movement_ledger_movement_type_movement_at_v019;
DROP INDEX IF EXISTS idx_inventory_movement_ledger_sku_location_movement_at_v019;
DROP INDEX IF EXISTS ux_inventory_movement_ledger_source_transfer_direction_v019;
DROP INDEX IF EXISTS ux_inventory_movement_ledger_source_adjustment_v019;
DROP INDEX IF EXISTS ux_inventory_movement_ledger_source_po_receipt_v019;
DROP INDEX IF EXISTS ux_inventory_movement_ledger_source_sale_v019;

DROP TABLE IF EXISTS inventory_movement_ledger;

DELETE FROM schema_table_comments
WHERE table_name IN ('inventory_movement_ledger', 'v_inventory_movement_reconciliation');

COMMIT;
