import { ALL_PERMISSIONS, PERMISSIONS as P } from './permissions';

export const ROLE_CATALOG = {
  OWNER: {
    name: 'OWNER',
    permissions: [...ALL_PERMISSIONS],
  },
  ADMIN: {
    name: 'ADMIN',
    permissions: [
      P.IDENTITY_ACCESS_MANAGE, P.IDENTITY_ACCESS_VIEW,
      P.EMPLOYEES_MANAGE, P.EMPLOYEES_VIEW,
      P.TIME_CLOCK_MANAGE, P.TIME_CLOCK_SELF,
      P.STORE_OPS_CONFIGURE, P.STORE_OPS_VIEW,
      P.PRODUCTS_WRITE, P.PRODUCTS_VIEW,
      P.INVENTORY_ADJUST, P.INVENTORY_VIEW,
      P.IMPORT_MANAGEMENT_VIEW, P.IMPORT_MANAGEMENT_RECEIVE_ESTIMATED,
      P.IMPORT_MANAGEMENT_FINAL_LIQUIDATION, P.IMPORT_MANAGEMENT_COST_OVERRIDE,
      P.IMPORT_MANAGEMENT_APPROVE_MISMATCH,
      P.PURCHASING_VIEW, P.OTB_VIEW, P.AR_VIEW,
      P.REPORTS_VIEW, P.SALES_POS_OPERATE,
      P.SEGMENTATION_READ, P.SEGMENTATION_WRITE, P.SEGMENTATION_ACTIVATE,
      P.SEGMENTATION_EVALUATE, P.SEGMENTATION_ADMIN,
    ],
  },
  FINANCE: {
    name: 'FINANCE',
    permissions: [
      P.TIME_CLOCK_SELF,
      P.AR_POST_PAYMENT, P.AR_VIEW,
      P.REPORTS_VIEW, P.STORE_OPS_VIEW,
      P.INVENTORY_VIEW, P.PRODUCTS_VIEW,
      P.IMPORT_MANAGEMENT_VIEW, P.IMPORT_MANAGEMENT_FINAL_LIQUIDATION,
    ],
  },
  BUYER: {
    name: 'BUYER',
    permissions: [
      P.TIME_CLOCK_SELF,
      P.PURCHASING_APPROVE, P.PURCHASING_EDIT, P.PURCHASING_VIEW,
      P.OTB_EDIT, P.OTB_VIEW,
      P.PRODUCTS_WRITE, P.PRODUCTS_VIEW,
      P.INVENTORY_VIEW, P.IMPORT_MANAGEMENT_VIEW, P.IMPORT_MANAGEMENT_RECEIVE_ESTIMATED,
      P.IMPORT_MANAGEMENT_COST_OVERRIDE, P.IMPORT_MANAGEMENT_APPROVE_MISMATCH,
      P.REPORTS_VIEW,
    ],
  },
  MANAGER: {
    name: 'MANAGER',
    permissions: [
      P.TIME_CLOCK_MANAGE, P.TIME_CLOCK_SELF,
      P.SALES_REFUND, P.SALES_POS_OPERATE,
      P.INVENTORY_VIEW, P.INVENTORY_ADJUST,
      P.PRODUCTS_VIEW, P.REPORTS_VIEW,
      P.STORE_OPS_VIEW, P.EMPLOYEES_VIEW,
      P.SEGMENTATION_READ,
    ],
  },
  SALESPERSON: {
    name: 'SALESPERSON',
    permissions: [
      P.TIME_CLOCK_SELF,
      P.SALES_POS_OPERATE,
      P.PRODUCTS_VIEW, P.INVENTORY_VIEW,
    ],
  },
} as const;

export type RoleName = keyof typeof ROLE_CATALOG;
export const ROLE_NAMES = Object.keys(ROLE_CATALOG) as RoleName[];
