import { MetricRegistryEntry, SegmentDefinitionSeed } from './types';

export const DEFAULT_SEGMENT_METRICS: MetricRegistryEntry[] = [
  {
    metricKey: 'first_purchase_at',
    displayName: 'First Purchase Date',
    description: 'Date of first purchase.',
    valueType: 'timestamp',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'first_purchase_at',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'exists', 'not_exists'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'last_purchase_at',
    displayName: 'Last Purchase Date',
    description: 'Date of most recent purchase.',
    valueType: 'timestamp',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'last_purchase_at',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'exists', 'not_exists'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'days_since_first_purchase',
    displayName: 'Days Since First Purchase',
    description: 'Number of days since first purchase.',
    valueType: 'integer',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'days_since_first_purchase',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'days_since_last_purchase',
    displayName: 'Days Since Last Purchase',
    description: 'Number of days since the most recent purchase.',
    valueType: 'integer',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'days_since_last_purchase',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'order_count_lifetime',
    displayName: 'Lifetime Order Count',
    description: 'Total completed orders.',
    valueType: 'integer',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'order_count_lifetime',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'order_count_30d',
    displayName: 'Order Count 30 Days',
    description: 'Orders in the last 30 days.',
    valueType: 'integer',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'order_count_30d',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'order_count_90d',
    displayName: 'Order Count 90 Days',
    description: 'Orders in the last 90 days.',
    valueType: 'integer',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'order_count_90d',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'order_count_365d',
    displayName: 'Order Count 365 Days',
    description: 'Orders in the last 365 days.',
    valueType: 'integer',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'order_count_365d',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'net_revenue_lifetime',
    displayName: 'Lifetime Net Revenue',
    description: 'Net revenue after returns and cancellations.',
    valueType: 'numeric',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'net_revenue_lifetime',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between', 'percentile_gte', 'percentile_lte'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'net_revenue_365d',
    displayName: 'Net Revenue 365 Days',
    description: 'Net revenue in the last 365 days after returns.',
    valueType: 'numeric',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'net_revenue_365d',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between', 'percentile_gte', 'percentile_lte'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'gross_margin_365d',
    displayName: 'Gross Margin 365 Days',
    description: 'Gross margin in the last 365 days.',
    valueType: 'numeric',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'gross_margin_365d',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between', 'percentile_gte', 'percentile_lte'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'avg_order_value_365d',
    displayName: 'Average Order Value 365 Days',
    description: 'Average order value in the last 365 days.',
    valueType: 'numeric',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'avg_order_value_365d',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between', 'percentile_gte', 'percentile_lte'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'return_count_365d',
    displayName: 'Return Count 365 Days',
    description: 'Return count in the last 365 days.',
    valueType: 'integer',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'return_count_365d',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'return_rate_365d',
    displayName: 'Return Rate 365 Days',
    description: 'Item or order return rate in the last 365 days.',
    valueType: 'numeric',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'return_rate_365d',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'markdown_revenue_share_365d',
    displayName: 'Markdown Revenue Share 365 Days',
    description: 'Share of revenue coming from markdown purchases.',
    valueType: 'numeric',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'markdown_revenue_share_365d',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'coupon_redemption_rate_365d',
    displayName: 'Coupon Redemption Rate 365 Days',
    description: 'Share of orders with coupon redemption.',
    valueType: 'numeric',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'coupon_redemption_rate_365d',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'full_price_purchase_count_365d',
    displayName: 'Full Price Purchase Count 365 Days',
    description: 'Full-price purchases in the last 365 days.',
    valueType: 'integer',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'full_price_purchase_count_365d',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'promo_purchase_count_365d',
    displayName: 'Promo Purchase Count 365 Days',
    description: 'Promotional purchases in the last 365 days.',
    valueType: 'integer',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'promo_purchase_count_365d',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'preferred_store_id',
    displayName: 'Preferred Store',
    description: 'Preferred store based on recent order behavior.',
    valueType: 'text',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'preferred_store_id',
    allowedOperators: ['=', '!=', 'in', 'not_in', 'exists', 'not_exists'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'preferred_channel',
    displayName: 'Preferred Channel',
    description: 'Preferred channel based on recent order behavior.',
    valueType: 'text',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'preferred_channel',
    allowedOperators: ['=', '!=', 'in', 'not_in', 'exists', 'not_exists'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'web_order_count_365d',
    displayName: 'Web Order Count 365 Days',
    description: 'Web orders in the last 365 days.',
    valueType: 'integer',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'web_order_count_365d',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'store_order_count_365d',
    displayName: 'Store Order Count 365 Days',
    description: 'Store orders in the last 365 days.',
    valueType: 'integer',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'store_order_count_365d',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'email_opt_in',
    displayName: 'Email Opt-In',
    description: 'Whether the customer can receive email.',
    valueType: 'boolean',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'email_opt_in',
    allowedOperators: ['=', '!='],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'sms_opt_in',
    displayName: 'SMS Opt-In',
    description: 'Whether the customer can receive SMS.',
    valueType: 'boolean',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'sms_opt_in',
    allowedOperators: ['=', '!='],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'push_opt_in',
    displayName: 'Push Opt-In',
    description: 'Whether the customer can receive push notifications.',
    valueType: 'boolean',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'push_opt_in',
    allowedOperators: ['=', '!='],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'employee_flag',
    displayName: 'Employee Flag',
    description: 'Whether the customer is marked as an employee.',
    valueType: 'boolean',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'employee_flag',
    allowedOperators: ['=', '!='],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'fraud_risk_flag',
    displayName: 'Fraud Risk Flag',
    description: 'Whether the customer is marked for fraud risk.',
    valueType: 'boolean',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'fraud_risk_flag',
    allowedOperators: ['=', '!='],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'abuse_risk_flag',
    displayName: 'Abuse Risk Flag',
    description: 'Whether the customer is marked for abuse risk.',
    valueType: 'boolean',
    sourceType: 'customer_feature',
    sourceTable: 'customer_features_current',
    sourceColumn: 'abuse_risk_flag',
    allowedOperators: ['=', '!='],
    supportsWindow: false,
    supportsDimension: false,
    dimensionConfig: null,
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'category_affinity_score',
    displayName: 'Category Affinity Score',
    description: 'Affinity score for a category.',
    valueType: 'numeric',
    sourceType: 'category_feature',
    sourceTable: 'customer_category_features',
    sourceColumn: 'affinity_score',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: true,
    dimensionConfig: { required: ['category_key'] },
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'category_purchase_count_365d',
    displayName: 'Category Purchase Count 365 Days',
    description: 'Purchase count in a category in the last 365 days.',
    valueType: 'integer',
    sourceType: 'category_feature',
    sourceTable: 'customer_category_features',
    sourceColumn: 'purchase_count_365d',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: true,
    dimensionConfig: { required: ['category_key'] },
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'brand_affinity_score',
    displayName: 'Brand Affinity Score',
    description: 'Affinity score for a brand.',
    valueType: 'numeric',
    sourceType: 'brand_feature',
    sourceTable: 'customer_brand_features',
    sourceColumn: 'affinity_score',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: true,
    dimensionConfig: { required: ['brand_key'] },
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'brand_purchase_count_365d',
    displayName: 'Brand Purchase Count 365 Days',
    description: 'Purchase count for a brand in the last 365 days.',
    valueType: 'integer',
    sourceType: 'brand_feature',
    sourceTable: 'customer_brand_features',
    sourceColumn: 'purchase_count_365d',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: true,
    dimensionConfig: { required: ['brand_key'] },
    sqlTemplate: null,
    isActive: true,
  },
  {
    metricKey: 'size_confidence_score',
    displayName: 'Size Confidence Score',
    description: 'Confidence that a customer buys a specific size.',
    valueType: 'numeric',
    sourceType: 'size_profile',
    sourceTable: 'customer_size_profiles',
    sourceColumn: 'confidence_score',
    allowedOperators: ['=', '!=', '>', '>=', '<', '<=', 'between'],
    supportsWindow: false,
    supportsDimension: true,
    dimensionConfig: { required: ['size_type', 'size_value'] },
    sqlTemplate: null,
    isActive: true,
  },
];

export const DEFAULT_SEGMENT_SEEDS: SegmentDefinitionSeed[] = [
  {
    segmentKey: 'prospects',
    name: 'Prospects',
    description: 'Known customers with no purchase yet.',
    segmentFamily: 'lifecycle',
    evaluationMode: 'batch',
    priority: 100,
    ruleAst: { all: [{ metric: 'order_count_lifetime', op: '=', value: 0 }] },
  },
  {
    segmentKey: 'new-customers',
    name: 'New Customers',
    description: 'Customers within 30 days of first purchase.',
    segmentFamily: 'lifecycle',
    evaluationMode: 'batch',
    priority: 90,
    ruleAst: {
      all: [
        { metric: 'order_count_lifetime', op: '>=', value: 1 },
        { metric: 'days_since_first_purchase', op: '<=', value: 30 },
      ],
    },
  },
  {
    segmentKey: 'one-time-buyers',
    name: 'One-Time Buyers',
    description: 'Customers with one order and enough time to chase a second purchase.',
    segmentFamily: 'lifecycle',
    evaluationMode: 'batch',
    priority: 85,
    ruleAst: {
      all: [
        { metric: 'order_count_lifetime', op: '=', value: 1 },
        { metric: 'days_since_first_purchase', op: '>', value: 14 },
      ],
    },
  },
  {
    segmentKey: 'repeat-customers',
    name: 'Repeat Customers',
    description: 'Customers with at least two orders.',
    segmentFamily: 'lifecycle',
    evaluationMode: 'batch',
    priority: 80,
    ruleAst: { all: [{ metric: 'order_count_lifetime', op: '>=', value: 2 }] },
  },
  {
    segmentKey: 'active-customers',
    name: 'Active Customers',
    description: 'Customers with a recent purchase in the last 90 days.',
    segmentFamily: 'lifecycle',
    evaluationMode: 'batch',
    priority: 70,
    ruleAst: {
      all: [
        { metric: 'order_count_lifetime', op: '>=', value: 1 },
        { metric: 'days_since_last_purchase', op: '<=', value: 90 },
      ],
    },
  },
  {
    segmentKey: 'lapsing-customers',
    name: 'Lapsing Customers',
    description: 'Customers drifting out of the active window.',
    segmentFamily: 'lifecycle',
    evaluationMode: 'batch',
    priority: 60,
    ruleAst: {
      all: [
        { metric: 'order_count_lifetime', op: '>=', value: 1 },
        { metric: 'days_since_last_purchase', op: 'between', value: [91, 180] },
      ],
    },
  },
  {
    segmentKey: 'lapsed-customers',
    name: 'Lapsed Customers',
    description: 'Customers with no purchase in more than 180 days.',
    segmentFamily: 'lifecycle',
    evaluationMode: 'batch',
    priority: 55,
    ruleAst: {
      all: [
        { metric: 'order_count_lifetime', op: '>=', value: 1 },
        { metric: 'days_since_last_purchase', op: '>', value: 180 },
      ],
    },
  },
  {
    segmentKey: 'vip-customers',
    name: 'VIP Customers',
    description: 'High-value repeat customers with acceptable return behavior.',
    segmentFamily: 'value',
    evaluationMode: 'batch',
    priority: 10,
    ruleAst: {
      all: [
        { metric: 'net_revenue_365d', op: '>=', value: 750 },
        { metric: 'order_count_lifetime', op: '>=', value: 3 },
        { metric: 'return_rate_365d', op: '<', value: 0.35 },
      ],
    },
  },
  {
    segmentKey: 'potential-vip-customers',
    name: 'Potential VIP Customers',
    description: 'Customers trending toward VIP value.',
    segmentFamily: 'value',
    evaluationMode: 'batch',
    priority: 20,
    ruleAst: {
      all: [
        { metric: 'order_count_lifetime', op: 'between', value: [1, 2] },
        { metric: 'net_revenue_365d', op: '>=', value: 300 },
        { metric: 'return_rate_365d', op: '<', value: 0.35 },
      ],
    },
  },
  {
    segmentKey: 'high-margin-customers',
    name: 'High Margin Customers',
    description: 'Customers who drive strong gross margin.',
    segmentFamily: 'value',
    evaluationMode: 'batch',
    priority: 30,
    ruleAst: { all: [{ metric: 'gross_margin_365d', op: '>=', value: 250 }] },
  },
  {
    segmentKey: 'high-aov-customers',
    name: 'High AOV Customers',
    description: 'Customers with large average baskets.',
    segmentFamily: 'value',
    evaluationMode: 'batch',
    priority: 35,
    ruleAst: {
      all: [
        { metric: 'avg_order_value_365d', op: '>=', value: 150 },
        { metric: 'order_count_365d', op: '>=', value: 2 },
      ],
    },
  },
  {
    segmentKey: 'frequent-buyers',
    name: 'Frequent Buyers',
    description: 'Customers with at least five orders in the last year.',
    segmentFamily: 'value',
    evaluationMode: 'batch',
    priority: 40,
    ruleAst: { all: [{ metric: 'order_count_365d', op: '>=', value: 5 }] },
  },
  {
    segmentKey: 'full-price-shoppers',
    name: 'Full-Price Shoppers',
    description: 'Customers who mostly buy outside markdown and coupon behavior.',
    segmentFamily: 'promo_behavior',
    evaluationMode: 'batch',
    priority: 25,
    ruleAst: {
      all: [
        { metric: 'full_price_purchase_count_365d', op: '>=', value: 2 },
        { metric: 'markdown_revenue_share_365d', op: '<', value: 0.25 },
        { metric: 'coupon_redemption_rate_365d', op: '<', value: 0.25 },
      ],
    },
  },
  {
    segmentKey: 'promo-responsive-customers',
    name: 'Promo-Responsive Customers',
    description: 'Customers who respond to coupons and promo inventory.',
    segmentFamily: 'promo_behavior',
    evaluationMode: 'batch',
    priority: 45,
    ruleAst: {
      all: [
        { metric: 'promo_purchase_count_365d', op: '>=', value: 2 },
        { metric: 'coupon_redemption_rate_365d', op: '>=', value: 0.3 },
      ],
    },
  },
  {
    segmentKey: 'coupon-dependent-customers',
    name: 'Coupon-Dependent Customers',
    description: 'Customers who mostly buy when a coupon is present.',
    segmentFamily: 'promo_behavior',
    evaluationMode: 'batch',
    priority: 50,
    ruleAst: {
      all: [
        { metric: 'order_count_365d', op: '>=', value: 2 },
        { metric: 'coupon_redemption_rate_365d', op: '>=', value: 0.7 },
      ],
    },
  },
  {
    segmentKey: 'clearance-buyers',
    name: 'Clearance Buyers',
    description: 'Customers with strong markdown share.',
    segmentFamily: 'promo_behavior',
    evaluationMode: 'batch',
    priority: 52,
    ruleAst: {
      all: [
        { metric: 'order_count_365d', op: '>=', value: 2 },
        { metric: 'markdown_revenue_share_365d', op: '>=', value: 0.7 },
      ],
    },
  },
  {
    segmentKey: 'store-only-customers',
    name: 'Store-Only Customers',
    description: 'Customers buying only in stores.',
    segmentFamily: 'channel_behavior',
    evaluationMode: 'batch',
    priority: 65,
    ruleAst: {
      all: [
        { metric: 'store_order_count_365d', op: '>=', value: 1 },
        { metric: 'web_order_count_365d', op: '=', value: 0 },
      ],
    },
  },
  {
    segmentKey: 'web-only-customers',
    name: 'Web-Only Customers',
    description: 'Customers buying only on web.',
    segmentFamily: 'channel_behavior',
    evaluationMode: 'batch',
    priority: 66,
    ruleAst: {
      all: [
        { metric: 'web_order_count_365d', op: '>=', value: 1 },
        { metric: 'store_order_count_365d', op: '=', value: 0 },
      ],
    },
  },
  {
    segmentKey: 'omnichannel-customers',
    name: 'Omnichannel Customers',
    description: 'Customers buying on web and in stores.',
    segmentFamily: 'channel_behavior',
    evaluationMode: 'batch',
    priority: 64,
    ruleAst: {
      all: [
        { metric: 'web_order_count_365d', op: '>=', value: 1 },
        { metric: 'store_order_count_365d', op: '>=', value: 1 },
      ],
    },
  },
  {
    segmentKey: 'at-risk-vip-customers',
    name: 'At-Risk VIP Customers',
    description: 'Former VIP customers drifting toward lapse.',
    segmentFamily: 'churn_risk',
    evaluationMode: 'batch',
    priority: 15,
    ruleAst: {
      all: [
        { metric: 'net_revenue_lifetime', op: '>=', value: 750 },
        { metric: 'order_count_lifetime', op: '>=', value: 3 },
        { metric: 'days_since_last_purchase', op: 'between', value: [120, 365] },
        { metric: 'return_rate_365d', op: '<', value: 0.35 },
      ],
    },
  },
  {
    segmentKey: 'high-return-rate-customers',
    name: 'High Return-Rate Customers',
    description: 'Customers with elevated return behavior.',
    segmentFamily: 'churn_risk',
    evaluationMode: 'batch',
    priority: 12,
    ruleAst: {
      all: [
        { metric: 'order_count_365d', op: '>=', value: 2 },
        { metric: 'return_rate_365d', op: '>=', value: 0.4 },
      ],
    },
  },
  {
    segmentKey: 'running-shoe-affinity',
    name: 'Running Shoe Customers',
    description: 'Customers with strong running shoe affinity.',
    segmentFamily: 'category_affinity',
    evaluationMode: 'batch',
    priority: 42,
    ruleAst: {
      all: [
        {
          metric: 'category_affinity_score',
          dimension: { category_key: 'running-shoes' },
          op: '>=',
          value: 0.7,
        },
      ],
    },
  },
  {
    segmentKey: 'sneaker-affinity',
    name: 'Sneaker Customers',
    description: 'Customers with strong sneaker affinity.',
    segmentFamily: 'category_affinity',
    evaluationMode: 'batch',
    priority: 43,
    ruleAst: {
      all: [
        {
          metric: 'category_affinity_score',
          dimension: { category_key: 'sneakers' },
          op: '>=',
          value: 0.7,
        },
      ],
    },
  },
  {
    segmentKey: 'kids-footwear-affinity',
    name: 'Kids Footwear Customers',
    description: 'Customers with strong kids footwear affinity.',
    segmentFamily: 'category_affinity',
    evaluationMode: 'batch',
    priority: 44,
    ruleAst: {
      all: [
        {
          metric: 'category_affinity_score',
          dimension: { category_key: 'kids-footwear' },
          op: '>=',
          value: 0.7,
        },
      ],
    },
  },
  {
    segmentKey: 'apparel-affinity',
    name: 'Apparel Customers',
    description: 'Customers with strong apparel affinity.',
    segmentFamily: 'category_affinity',
    evaluationMode: 'batch',
    priority: 46,
    ruleAst: {
      all: [
        {
          metric: 'category_affinity_score',
          dimension: { category_key: 'apparel' },
          op: '>=',
          value: 0.7,
        },
      ],
    },
  },
];
